module.exports = {
  docs: {
    Guides: ['docs-home'],
    JavaScript: [
      'javascript/array',
      'javascript/async-function',
      'javascript/compose',
      'javascript/function-declaration-instantiation',
      'javascript/generator',
      'javascript/iteration-protocols',
      'javascript/map',
      'javascript/object',
      'javascript/promise',
      'javascript/regexp',
      'javascript/set',
      'javascript/string',
      'javascript/this',
      'javascript/var-let-const',
      'javascript/closure',
    ],
    TypeScript: [
      'typescript/basic-types',
      'typescript/interface',
      'typescript/class',
    ],
    React: ['react/concepts'],
    Webpack: ['webpack/concepts'],
    CSS: ['css/flex', 'css/css-in-head'],
    Html: [
      'html/data-attributes',
      'html/microtask',
      'html/storage-api',
      'html/xhr',
      'html/add-event-listener',
      'html/script',
    ],
    Http: [
      'http/overview',
      'http/caching',
      'http/server-sent-events',
      'http/content-security-policy',
      'http/cookie',
      'http/cors',
      'http/cors-solutions',
      'http/methods',
      'http/status-codes',
      'http/headers',
    ],
    Algorithm: ['algorithm/fibonacci'],
    Github: ['github/webhooks'],
    Snippets: ['snippets/random-key', 'snippets/detect-browser'],
    Bash: ['bash/bash-if', 'bash/tar'],
    Linux: ['linux/directory'],
    Chrome: ['chrome/chrome-error'],
    Mirrors: ['mirrors/taobao-npm-mirrors'],
  },
};
