module.exports = {
  docs: {
    Guides: ['docs-home'],
    JavaScript: [
      'javascript/array',
      'javascript/async-function',
      'javascript/compose',
      'javascript/function-declaration-instantiation',
      'javascript/generator',
      'javascript/iteration-protocols',
      'javascript/map',
      'javascript/object',
      'javascript/promise',
      'javascript/regexp',
      'javascript/set',
      'javascript/string',
      'javascript/this',
    ],
    TypeScript: [
      'typescript/basic-types',
      'typescript/interface',
      'typescript/class',
    ],
    React: ['react/concepts'],
    Webpack: ['webpack/concepts'],
    Html: ['html/data-attributes', 'html/microtask', 'html/storage-api'],
    Http: [
      'http/overview',
      'http/caching',
      'http/server-sent-events',
      'http/content-security-policy',
      'http/cookie',
      'http/cors',
      'http/methods',
      'http/status-codes',
    ],
    Snippets: ['snippets/random-key', 'snippets/detect-browser'],
    Bash: ['bash/bash-if'],
    Mirrors: ['mirrors/taobao-npm-mirrors'],
  },
};
